spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  paths-to-match: /**

logging:
  level:
    org.springframework: DEBUG
    org.springdoc: DEBUG
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 360000